# Generated by Django 4.2.7 on 2023-12-01 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HelloWorldApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='recipient',
            field=models.CharField(default='DefaultValue', max_length=50),
        ),
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.CharField(default='DefaultSender', max_length=50),
        ),
        migrations.AddField(
            model_name='message',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(),
        ),
    ]
