# Generated by Django 4.2.7 on 2024-01-12 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HelloWorldApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='content',
        ),
        migrations.AddField(
            model_name='message',
            name='text',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
