# Generated by Django 4.2.7 on 2024-01-10 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HelloWorldApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
